/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"

namespace KBEngine
{

class Entity;
class DATATYPE_BASE;
class ScriptModule;

// Manage descriptions of all entities

class KBENGINEPLUGINS_API EntityDef
{
public:
	static TMap<FString, uint16> datatype2id;
	static TMap<FString, DATATYPE_BASE*> datatypes;
	static TMap<uint16, DATATYPE_BASE*> id2datatypes;
	static TMap<FString, int32> entityclass;
	static TMap<FString, ScriptModule*> moduledefs;
	static TMap<uint16, ScriptModule*> idmoduledefs;

	static bool initialize();
	static bool reset();
	static void clear();
	static void initDataTypes();
	static void initScriptModules();
	static void initDefTypes();
	static Entity* createEntity(int utype);
};

}