/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/SpaceDuplicate.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_SpaceDuplicateBase : public EntityCall
{
public:

	EntityBaseEntityCall_SpaceDuplicateBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_SpaceDuplicateBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_SpaceDuplicateBase : public EntityCall
{
public:

	EntityCellEntityCall_SpaceDuplicateBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_SpaceDuplicateBase();
};

}