/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/SpawnPoint.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_SpawnPointBase : public EntityCall
{
public:

	EntityBaseEntityCall_SpawnPointBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_SpawnPointBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_SpawnPointBase : public EntityCall
{
public:

	EntityCellEntityCall_SpawnPointBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_SpawnPointBase();
};

}