/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/Monster.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_MonsterBase : public EntityCall
{
public:

	EntityBaseEntityCall_MonsterBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_MonsterBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_MonsterBase : public EntityCall
{
public:

	EntityCellEntityCall_MonsterBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_MonsterBase();
};

}