/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"

// defined in */scripts/entity_defs/Space.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_SpaceBase : public EntityCall
{
public:
	EntityBaseEntityCall_SpaceBase() : EntityCall()
	{
		type = ENTITYCALL_TYPE_BASE;
	}

};

class KBENGINEPLUGINS_API EntityCellEntityCall_SpaceBase : public EntityCall
{
public:
	EntityCellEntityCall_SpaceBase() : EntityCall()
	{
		type = ENTITYCALL_TYPE_CELL;
	}

};

}