/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"

// defined in */scripts/entity_defs/Avatar.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_AvatarBase : public EntityCall
{
public:
	EntityBaseEntityCall_AvatarBase() : EntityCall()
	{
		type = ENTITYCALL_TYPE_BASE;
	}

};

class KBENGINEPLUGINS_API EntityCellEntityCall_AvatarBase : public EntityCall
{
public:
	EntityCellEntityCall_AvatarBase() : EntityCall()
	{
		type = ENTITYCALL_TYPE_CELL;
	}

	void dialog(int32 arg1, uint32 arg2);
	void jump();
	void relive(uint8 arg1);
	void requestPull();
	void useTargetSkill(int32 arg1, int32 arg2);
};

}